# Generated by Django 4.2.20 on 2025-04-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_order_email_order_phone_alter_order_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_data',
            field=models.TextField(default='empty'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(default='000000000'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(default='000000000', max_length=15),
        ),
    ]
