# Generated by Django 4.2.20 on 2025-04-15 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_order_cart_data_order_total_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
